-- AlterTable
ALTER TABLE "DeliveryProject" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "DeliveryProject" ADD COLUMN IF NOT EXISTS "paidAt" TIMESTAMP(3);
